### ISSUE TITLE
Fine-Tuning colab error

### ISSUE THREAD

**Issue by joelbudu** [huggingface/parler-tts#46] opened 2024-05-12 10:33 UTC
Hello, I'm trying to run the exact fine-tuning script in the colab notebook. But there's an error on the cell below with the following output.

```
!python main.py "ylacombe/jenny-tts-6h" \
  --configuration "default" \
  --text_column_name "transcription" \
  --audio_column_name "audio" \
  --cpu_num_workers 2 \
  --num_workers_per_gpu_for_pitch 2 \
  --rename_column \
  --repo_id "jenny-tts-tags-6h"
```

```
main.py 52 <module>
snr_dataset = dataset.map(

dataset_dict.py 869 map
{

dataset_dict.py 870 <dictcomp>
k: dataset.map(

arrow_dataset.py 602 wrapper
out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)

arrow_dataset.py 567 wrapper
out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)

arrow_dataset.py 3156 map
for rank, done, content in Dataset._map_single(**dataset_kwargs):

arrow_dataset.py 3547 _map_single
batch = apply_function_on_filtered_inputs(

arrow_dataset.py 3416 apply_function_on_filtered_inputs
processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)

snr_and_reverb.py 22 snr_apply
pipeline = RegressiveActivityDetectionPipeline(segmentation=model)

pipeline.py 72 __init__
self._frames = self._segmentation.model.example_output.frames

module.py 1688 __getattr__
raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

AttributeError:
'CustomPyanNetModel' object has no attribute 'example_output'
```

**Comment by yoesak** [comment] 2024-05-12 11:38
@ylacombe this is the same issue that I mention you in [here]( https://huggingface.co/ylacombe/brouhaha-best/discussions/2#663cd5551785c9e676ee4aa3)

**Comment by ylacombe** [comment] 2024-05-13 07:51
Hey everyone, the issue is coming from the library brouhaha and I've opened a PR to correct it [here](https://github.com/marianne-m/brouhaha-vad/pull/21).
In the meantime, a quick fix would be to install an older Pyannote version like this:
`pip install -U pyannote.audio==3.1.1`
It should fix the issue, let me know if it works!

**Comment by grigoriy-a** [comment] 2024-05-14 19:49
@ylacombe thanks, that helped

**Comment by joelbudu** [comment] 2024-05-14 19:50
Thanks @ylacombe that workaround works

**Comment by ylacombe** [comment] 2024-05-27 09:11
[It has been fixed and merged](https://github.com/marianne-m/brouhaha-vad/pull/21). If you reinstall brouhaha from scratch, the error should disappear!
Closing for now, but feel free to re-open if necessary!

**Closed by ylacombe** 2024-05-27 09:11 UTC
